[project]
name = "uptime-cli-plugin"
version = "0.1.0"
description = "Show uptime CLI command"
readme = "README.md"
requires-python = "~=3.11"
dependencies = [
    "jinja2==3.1.2",
    "mypy==1.11.0",
    "mypy-extensions==1.0.0",
]

[dependency-groups]
dev = ["ruff>=0.9.5"]