#!/bin/bash

function deploy-lab {
    clab dep -c
}

function destroy-lab {
    clab des -c
}

#########################################
#### Dev env functions
#########################################
function get-srl-venv-requirements {
    # get the venv requirements from the container and exlude local packages (@ file)
    sudo docker exec -i -t srl /opt/srlinux/python/virtual-env/bin/pip freeze | grep -v '@ file' > requirements.txt
}

function get-uv {
    curl -LsSf https://astral.sh/uv/install.sh | sh
}

# install fetched requirements to the local venv
function install-deps {
    uv add --requirements requirements.txt
}


# copy out the srlinux cli package from the container to the host.
# will be available in ./src/srlinux directory
function fetch-srl-cli {
    sudo docker cp srl:/opt/srlinux/python/virtual-env/lib/python3.11/dist-packages/srlinux ./src
}

$@